### ISSUE TITLE
Aggregate inputted data from database

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#18]
Epic: #3 

### Description
As a user, I want the data provided to be combined and used to generate a schedule automatically.

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by salsajeries** [comment]
@september-a Correct me if I'm wrong, but this story is probably complete by now? My understanding is that this is just "can we pull data from the database to make a schedule"

**Comment by september-a** [comment]
@salsajeries Yeah I think you are right. That is the way I am interpreting it and we are doing that.

**Comment by salsajeries** [comment]
We did this at some point so marking as closed
