### ISSUE TITLE
Database tables not dropped properly

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#77]
For some reason, the generate schedule API endpoint cannot be used more than once in a session. We think this could be caused by:

- Improper database clearing/dropping tables
- Something else we don't know that's pretty much all we could think of

When we try to generate a second time, the docker container shows that python has issues. That would be something good to look at.

**Comment by september-a** [comment]
photo of issue for reference 
<img width="828" alt="Screenshot 2024-04-03 at 4 04 53 PM" src="https://github.com/BSSD-Technologies/ChargerSync/assets/97040169/b1496caa-f669-444e-8bfc-ae39b9512dc1">

**Comment by september-a** [comment]
There is so much I do not understand about this issue

**Comment by salsajeries** [comment]
Forgive my ignorance bc I haven't actually gotten the chance to look at the solutions yall have tried implementing, but i found this:

https://stackoverflow.com/questions/11233128/how-to-clean-the-database-dropping-all-records-using-sqlalchemy

Idk if our models "define the complete schema" or not haha

**Comment by september-a** [comment]
Have a potential solution to this on sept-dev branch.

Database should be appropriately reflecting the messages being sent to backend. However this does not mean scheduling on second iteration is properly fixed
